# Generated by Django 5.0.2 on 2024-03-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post',
            new_name='post',
        ),
    ]
